[package]
name = "charred_ravine"
version = "0.0.1"
authors = ["SIOCODE Llc. <info@siocode.hu>"]
edition = "2021"

[dependencies]
ink = { workspace = true }


[lib]
path = "lib.rs"

[features]
default = ["std"]
std = ["ink/std"]
ink-as-dependency = []