[package]
name = "metcrys_creator"
version = "0.1.0"
authors = ["[Frank Dierolf] <[frank_dierolf@web.de]>"]
edition = "2021"

[dependencies]
ink = { version = "5.0.0", default-features = false }
other-contract = { path = "other-contract", default-features = false, features = [
  "ink-as-dependency",
] }
metal = { path = "metal", default-features = false, features = [
  "ink-as-dependency",
] }
crystal = { path = "crystal", default-features = false, features = [
  "ink-as-dependency",
] }
metcrys = { path = "metcrys", default-features = false, features = [
  "ink-as-dependency",
] }

[lib]
path = "lib.rs"

[features]
std = [
  "ink/std",
  "other-contract/std",
  "metal/std",
  "crystal/std",
  "metcrys/std",
]
default = ["std"]
ink-as-dependency = []
