[package]
name = "a_contract"
version = "0.1.0"
authors = ["[Frank Dierolf] <[frank_dierolf@web.de]>"]
edition = "2021"

[dependencies]
ink = { version = "5.0.0", default-features = false }

[lib]
path = "lib.rs"

[features]
std = ["ink/std"]
default = ["std"]
ink-as-dependency = []
