[package]
name = "contracts"
version = "0.1.0"
authors = ["[Frank Dierolf] <[frank_dierolf@web.de]>"]
edition = "2021"

[dependencies]
ink = { version = "5.0.0", default-features = false }
other-contract = { path = "other-contract", default-features = false, features = [
  "ink-as-dependency",
] }
rock = { path = "rock", default-features = false, features = [
  "ink-as-dependency",
] }


[dev-dependencies]
ink_e2e = { version = "5.0.0" }

[lib]
path = "lib.rs"

[features]
std = ["ink/std", "other-contract/std", "rock/std"]
default = ["std"]
ink-as-dependency = []
e2e-tests = []
